### PR TITLE
po: update Chinese simplified translation

### PR DESCRIPTION
**Pull request by dirtycold**
updated zh_CN translation:

* added translation to new strings
* fixed fuzzy strings

Signed-off-by: ZH <zhanghan@gmx.cn>

### CODE REVIEW

**Comment by davvid** [comment]
@Vdragon ack?

**Comment by Vdragon** [comment]
@dirtycold You shouldn't translate the square bracket part of `msgid` in `po/glossary/zh_cn.po`, which is used just to differentiate noun/verb form of those terms.

Else LGFM.

**Comment by dirtycold** [comment]
Hi. Thanks for reminding!

Just checked zh_TW translation. I'll edit the translation later.

**Comment by dirtycold** [comment]
@Vdragon just updated :-)

**Comment by davvid** [comment]
@Vdragon please feel free to merge this if it looks good to you.  Thanks!

**Comment by Vdragon** [comment]
LGFM.

**Pull request merged**
